import { DiscoverCategory, DiscoverFeed } from "@/types/discover";

/**
 * Curated collection of high-quality RSS feeds organized by category.
 * These are manually selected feeds that are known to be reliable and valuable.
 * All feeds have been tested and verified to work.
 */
export const CURATED_FEEDS: Record<DiscoverCategory, DiscoverFeed[]> = {
  "youtube": [
    {
      id: "curated-yt-1",
      name: "MKBHD",
      description: "Quality tech videos from Marques Brownlee",
      feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCBJycsmduvYEL83R_U4JriQ",
      siteUrl: "https://www.youtube.com/@mkbhd",
      category: "youtube",
      source: "curated",
      popularity: 100,
      tags: ["Tech", "Reviews"],
      isYouTube: true,
    },
    {
      id: "curated-yt-2",
      name: "Fireship",
      description: "Fast-paced coding tutorials and tech news in 100 seconds",
      feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCsBjURrPoezykLs9EqgamOA",
      siteUrl: "https://www.youtube.com/@Fireship",
      category: "youtube",
      source: "curated",
      popularity: 98,
      tags: ["Coding", "Tutorials"],
      isYouTube: true,
    },
    {
      id: "curated-yt-3",
      name: "Linus Tech Tips",
      description: "Tech tips, unboxing, and reviews",
      feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCXuqSBlHAE6Xw-yeJA0Tunw",
      siteUrl: "https://www.youtube.com/@LinusTechTips",
      category: "youtube",
      source: "curated",
      popularity: 95,
      tags: ["Tech", "Reviews"],
      isYouTube: true,
    },
    {
      id: "curated-yt-4",
      name: "Veritasium",
      description: "Science and engineering videos with stunning visuals",
      feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCHnyfMqiRRG1u-2MsSQLbXA",
      siteUrl: "https://www.youtube.com/@veritasium",
      category: "youtube",
      source: "curated",
      popularity: 92,
      tags: ["Science", "Education"],
      isYouTube: true,
    },
    {
      id: "curated-yt-5",
      name: "3Blue1Brown",
      description: "Animated math explanations",
      feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCYO_jab_esuFRV4b17AJtAw",
      siteUrl: "https://www.youtube.com/@3blue1brown",
      category: "youtube",
      source: "curated",
      popularity: 90,
      tags: ["Math", "Education"],
      isYouTube: true,
    },
    {
      id: "curated-yt-6",
      name: "Theo - t3.gg",
      description: "Web development, React, and TypeScript content",
      feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCbRP3c757lWg9M-U7TyEkXA",
      siteUrl: "https://www.youtube.com/@t3dotgg",
      category: "youtube",
      source: "curated",
      popularity: 88,
      tags: ["Web Dev", "React"],
      isYouTube: true,
    },
    {
      id: "curated-yt-7",
      name: "The Primeagen",
      description: "Programming, Vim, and developer content",
      feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UC8ENHE5xdFSwx71u3fDH5Xw",
      siteUrl: "https://www.youtube.com/@ThePrimeagen",
      category: "youtube",
      source: "curated",
      popularity: 86,
      tags: ["Programming", "Vim"],
      isYouTube: true,
    },
    {
      id: "curated-yt-8",
      name: "Traversy Media",
      description: "Web development tutorials and crash courses",
      feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UC29ju8bIPH5as8OGnQzwJyA",
      siteUrl: "https://www.youtube.com/@TraversyMedia",
      category: "youtube",
      source: "curated",
      popularity: 85,
      tags: ["Web Dev", "Tutorials"],
      isYouTube: true,
    },
    {
      id: "curated-yt-9",
      name: "Lex Fridman",
      description: "Podcast conversations about AI, science, and life",
      feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCSHZKyawb77ixDdsGog4iWA",
      siteUrl: "https://www.youtube.com/@lexfridman",
      category: "youtube",
      source: "curated",
      popularity: 94,
      tags: ["AI", "Podcast"],
      isYouTube: true,
    },
    {
      id: "curated-yt-10",
      name: "Two Minute Papers",
      description: "AI and machine learning research explained",
      feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCbfYPyITQ-7l4upoX8nvctg",
      siteUrl: "https://www.youtube.com/@TwoMinutePapers",
      category: "youtube",
      source: "curated",
      popularity: 82,
      tags: ["AI", "Research"],
      isYouTube: true,
    },
    {
      id: "curated-yt-11",
      name: "Kurzgesagt – In a Nutshell",
      description: "Beautifully animated science explainers",
      feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCsXVk37bltHxD1rDPwtNM8Q",
      siteUrl: "https://www.youtube.com/@kurzgesagt",
      category: "youtube",
      source: "curated",
      popularity: 96,
      tags: ["Science", "Animation"],
      isYouTube: true,
    },
    {
      id: "curated-yt-12",
      name: "Tom Scott",
      description: "Fascinating facts about language, technology, and more",
      feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCBa659QWEk1AI4Tg--mrJ2A",
      siteUrl: "https://www.youtube.com/@TomScottGo",
      category: "youtube",
      source: "curated",
      popularity: 91,
      tags: ["Education", "Tech"],
      isYouTube: true,
    },
    {
      id: "curated-yt-13",
      name: "NetworkChuck",
      description: "Networking, cybersecurity, and IT tutorials",
      feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UC9x0AN7BWHpCDHSm9NiJFJQ",
      siteUrl: "https://www.youtube.com/@NetworkChuck",
      category: "youtube",
      source: "curated",
      popularity: 84,
      tags: ["Networking", "IT"],
      isYouTube: true,
    },
    {
      id: "curated-yt-14",
      name: "Web Dev Simplified",
      description: "Making web development simple and fun",
      feedUrl: "https://www.youtube.com/feeds/videos.xml?channel_id=UCFbNIlppjAuEX4znoulh0Cw",
      siteUrl: "https://www.youtube.com/@WebDevSimplified",
      category: "youtube",
      source: "curated",
      popularity: 80,
      tags: ["Web Dev", "Tutorials"],
      isYouTube: true,
    },
  ],
  "ai-ml": [
    {
      id: "curated-ai-1",
      name: "Distill.pub",
      description: "Clear explanations of machine learning research",
      feedUrl: "https://distill.pub/rss.xml",
      siteUrl: "https://distill.pub",
      category: "ai-ml",
      source: "curated",
      popularity: 100,
      tags: ["AI", "Research", "Explainers"],
    },
    {
      id: "curated-ai-2",
      name: "Google AI Blog",
      description: "Latest news and research from Google AI",
      feedUrl: "https://blog.google/technology/ai/rss/",
      siteUrl: "https://blog.google/technology/ai/",
      category: "ai-ml",
      source: "curated",
      popularity: 98,
      tags: ["AI", "Google", "Research"],
    },
    {
      id: "curated-ai-3",
      name: "Hugging Face Blog",
      description: "Open source ML tools and models",
      feedUrl: "https://huggingface.co/blog/feed.xml",
      siteUrl: "https://huggingface.co/blog",
      category: "ai-ml",
      source: "curated",
      popularity: 95,
      tags: ["ML", "Open Source"],
    },
    {
      id: "curated-ai-4",
      name: "The Gradient",
      description: "Perspectives on AI research and applications",
      feedUrl: "https://thegradient.pub/rss/",
      siteUrl: "https://thegradient.pub",
      category: "ai-ml",
      source: "curated",
      popularity: 90,
      tags: ["AI", "Research"],
    },
    {
      id: "curated-ai-5",
      name: "Machine Learning Mastery",
      description: "Practical machine learning tutorials",
      feedUrl: "https://machinelearningmastery.com/feed/",
      siteUrl: "https://machinelearningmastery.com",
      category: "ai-ml",
      source: "curated",
      popularity: 88,
      tags: ["ML", "Tutorials"],
    },
    {
      id: "curated-ai-6",
      name: "Weights & Biases Blog",
      description: "ML experiment tracking and insights",
      feedUrl: "https://wandb.ai/site/feed",
      siteUrl: "https://wandb.ai/site",
      category: "ai-ml",
      source: "curated",
      popularity: 85,
      tags: ["ML", "Tools"],
    },
    {
      id: "curated-ai-7",
      name: "AI Alignment Forum",
      description: "Discussions on AI safety and alignment",
      feedUrl: "https://www.alignmentforum.org/feed.xml",
      siteUrl: "https://www.alignmentforum.org",
      category: "ai-ml",
      source: "curated",
      popularity: 82,
      tags: ["AI Safety", "Research"],
    },
    {
      id: "curated-ai-8",
      name: "Papers With Code",
      description: "Latest ML papers with code implementations",
      feedUrl: "https://paperswithcode.com/rss/latest",
      siteUrl: "https://paperswithcode.com",
      category: "ai-ml",
      source: "curated",
      popularity: 92,
      tags: ["ML", "Papers", "Code"],
    },
    {
      id: "curated-ai-9",
      name: "Towards Data Science",
      description: "Data science and ML articles",
      feedUrl: "https://towardsdatascience.com/feed",
      siteUrl: "https://towardsdatascience.com",
      category: "ai-ml",
      source: "curated",
      popularity: 87,
      tags: ["Data Science", "ML"],
    },
    {
      id: "curated-ai-10",
      name: "LessWrong",
      description: "Rationality and AI safety discussions",
      feedUrl: "https://www.lesswrong.com/feed.xml",
      siteUrl: "https://www.lesswrong.com",
      category: "ai-ml",
      source: "curated",
      popularity: 80,
      tags: ["AI Safety", "Rationality"],
    },
  ],
  "social-media": [
    {
      id: "curated-social-1",
      name: "Hacker News - Front Page",
      description: "Top stories from Y Combinator's Hacker News",
      feedUrl: "https://hnrss.org/frontpage",
      siteUrl: "https://news.ycombinator.com",
      category: "social-media",
      source: "curated",
      popularity: 100,
      tags: ["Tech", "Startups"],
    },
    {
      id: "curated-social-2",
      name: "Hacker News - Best",
      description: "Best stories from Hacker News",
      feedUrl: "https://hnrss.org/best",
      siteUrl: "https://news.ycombinator.com/best",
      category: "social-media",
      source: "curated",
      popularity: 98,
      tags: ["Tech", "Startups"],
    },
    {
      id: "curated-social-3",
      name: "Hacker News - New",
      description: "Newest stories from Hacker News",
      feedUrl: "https://hnrss.org/newest",
      siteUrl: "https://news.ycombinator.com/newest",
      category: "social-media",
      source: "curated",
      popularity: 90,
      tags: ["Tech", "Startups"],
    },
    {
      id: "curated-social-4",
      name: "Lobsters",
      description: "Computing-focused community link aggregation",
      feedUrl: "https://lobste.rs/rss",
      siteUrl: "https://lobste.rs",
      category: "social-media",
      source: "curated",
      popularity: 95,
      tags: ["Tech", "Programming"],
    },
    {
      id: "curated-social-5",
      name: "Lobsters - Newest",
      description: "Newest stories on Lobsters",
      feedUrl: "https://lobste.rs/newest.rss",
      siteUrl: "https://lobste.rs/newest",
      category: "social-media",
      source: "curated",
      popularity: 92,
      tags: ["Tech", "Programming"],
    },
    {
      id: "curated-social-6",
      name: "Echo JS",
      description: "JavaScript news and articles",
      feedUrl: "https://www.echojs.com/rss",
      siteUrl: "https://www.echojs.com",
      category: "social-media",
      source: "curated",
      popularity: 85,
      tags: ["JavaScript", "Web Dev"],
    },
    {
      id: "curated-social-7",
      name: "DEV Community",
      description: "Community of software developers",
      feedUrl: "https://dev.to/feed",
      siteUrl: "https://dev.to",
      category: "social-media",
      source: "curated",
      popularity: 88,
      tags: ["Programming", "Community"],
    },
    {
      id: "curated-social-8",
      name: "Hashnode",
      description: "Developer blogging platform",
      feedUrl: "https://hashnode.com/feed",
      siteUrl: "https://hashnode.com",
      category: "social-media",
      source: "curated",
      popularity: 82,
      tags: ["Programming", "Blogs"],
    },
    {
      id: "curated-social-9",
      name: "Product Hunt - Daily",
      description: "Discover new products every day",
      feedUrl: "https://www.producthunt.com/feed",
      siteUrl: "https://www.producthunt.com",
      category: "social-media",
      source: "curated",
      popularity: 90,
      tags: ["Products", "Startups"],
    },
    {
      id: "curated-social-10",
      name: "Designer News",
      description: "Community-curated design news",
      feedUrl: "https://www.designernews.co/?format=rss",
      siteUrl: "https://www.designernews.co",
      category: "social-media",
      source: "curated",
      popularity: 78,
      tags: ["Design", "Community"],
    },
    {
      id: "curated-social-11",
      name: "Sidebar.io",
      description: "5 best design links every day",
      feedUrl: "https://sidebar.io/feed.xml",
      siteUrl: "https://sidebar.io",
      category: "social-media",
      source: "curated",
      popularity: 80,
      tags: ["Design", "Links"],
    },
  ],
  "design-creative": [
    {
      id: "curated-design-1",
      name: "Dribbble Blog",
      description: "Design inspiration and community stories",
      feedUrl: "https://dribbble.com/stories.rss",
      siteUrl: "https://dribbble.com/stories",
      category: "design-creative",
      source: "curated",
      popularity: 95,
      tags: ["Design", "Inspiration"],
    },
    {
      id: "curated-design-2",
      name: "Design Observer",
      description: "Critical writing about design and visual culture",
      feedUrl: "https://designobserver.com/feed/",
      siteUrl: "https://designobserver.com",
      category: "design-creative",
      source: "curated",
      popularity: 92,
      tags: ["Design", "Culture"],
    },
    {
      id: "curated-design-3",
      name: "Creative Bloq",
      description: "Graphic design, 3D, digital art, and more",
      feedUrl: "https://www.creativebloq.com/feeds/all",
      siteUrl: "https://www.creativebloq.com",
      category: "design-creative",
      source: "curated",
      popularity: 88,
      tags: ["Design", "Tutorials"],
    },
    {
      id: "curated-design-4",
      name: "Codrops",
      description: "Useful resources and inspiration for web design",
      feedUrl: "https://tympanus.net/codrops/feed/",
      siteUrl: "https://tympanus.net/codrops",
      category: "design-creative",
      source: "curated",
      popularity: 90,
      tags: ["Web Design", "CSS"],
    },
    {
      id: "curated-design-5",
      name: "UX Collective",
      description: "Curated stories on user experience",
      feedUrl: "https://uxdesign.cc/feed",
      siteUrl: "https://uxdesign.cc",
      category: "design-creative",
      source: "curated",
      popularity: 87,
      tags: ["UX", "Design"],
    },
    {
      id: "curated-design-6",
      name: "Nielsen Norman Group",
      description: "Evidence-based UX research and design",
      feedUrl: "https://www.nngroup.com/feed/rss/",
      siteUrl: "https://www.nngroup.com",
      category: "design-creative",
      source: "curated",
      popularity: 85,
      tags: ["UX", "Research"],
    },
    {
      id: "curated-design-7",
      name: "99U",
      description: "Insights on making ideas happen",
      feedUrl: "https://99u.adobe.com/feed",
      siteUrl: "https://99u.adobe.com",
      category: "design-creative",
      source: "curated",
      popularity: 82,
      tags: ["Creativity", "Productivity"],
    },
    {
      id: "curated-design-8",
      name: "Muzli Design Weekly",
      description: "Design inspiration and resources",
      feedUrl: "https://medium.com/feed/muzli-design-inspiration",
      siteUrl: "https://muz.li",
      category: "design-creative",
      source: "curated",
      popularity: 80,
      tags: ["Design", "Inspiration"],
    },
    {
      id: "curated-design-9",
      name: "Swiss Miss",
      description: "Design blog by Tina Roth Eisenberg",
      feedUrl: "https://www.swiss-miss.com/feed",
      siteUrl: "https://www.swiss-miss.com",
      category: "design-creative",
      source: "curated",
      popularity: 78,
      tags: ["Design", "Inspiration"],
    },
    {
      id: "curated-design-10",
      name: "Designmodo",
      description: "Web design tools and resources",
      feedUrl: "https://designmodo.com/feed/",
      siteUrl: "https://designmodo.com",
      category: "design-creative",
      source: "curated",
      popularity: 84,
      tags: ["Web Design", "Tools"],
    },
    {
      id: "curated-design-11",
      name: "Abduzeedo",
      description: "Design inspiration and tutorials",
      feedUrl: "https://abduzeedo.com/feed",
      siteUrl: "https://abduzeedo.com",
      category: "design-creative",
      source: "curated",
      popularity: 76,
      tags: ["Design", "Tutorials"],
    },
  ],
  "tech-programming": [
    {
      id: "curated-tech-1",
      name: "The Verge",
      description: "Technology, science, art, and culture news",
      feedUrl: "https://www.theverge.com/rss/index.xml",
      siteUrl: "https://www.theverge.com",
      category: "tech-programming",
      source: "curated",
      popularity: 100,
      tags: ["Tech News", "Culture"],
    },
    {
      id: "curated-tech-2",
      name: "Ars Technica",
      description: "Original news and reviews for tech enthusiasts",
      feedUrl: "https://feeds.arstechnica.com/arstechnica/index",
      siteUrl: "https://arstechnica.com",
      category: "tech-programming",
      source: "curated",
      popularity: 95,
      tags: ["Tech News", "Reviews"],
    },
    {
      id: "curated-tech-3",
      name: "TechCrunch",
      description: "Startup and technology news",
      feedUrl: "https://techcrunch.com/feed/",
      siteUrl: "https://techcrunch.com",
      category: "tech-programming",
      source: "curated",
      popularity: 90,
      tags: ["Startups", "Tech News"],
    },
    {
      id: "curated-tech-4",
      name: "CSS-Tricks",
      description: "Web design and development articles",
      feedUrl: "https://css-tricks.com/feed/",
      siteUrl: "https://css-tricks.com",
      category: "tech-programming",
      source: "curated",
      popularity: 85,
      tags: ["CSS", "Web Dev"],
    },
    {
      id: "curated-tech-5",
      name: "Smashing Magazine",
      description: "For web designers and developers",
      feedUrl: "https://www.smashingmagazine.com/feed/",
      siteUrl: "https://www.smashingmagazine.com",
      category: "tech-programming",
      source: "curated",
      popularity: 80,
      tags: ["Web Dev", "Design"],
    },
    {
      id: "curated-tech-6",
      name: "A List Apart",
      description: "Web design, development, and content strategy",
      feedUrl: "https://alistapart.com/main/feed/",
      siteUrl: "https://alistapart.com",
      category: "tech-programming",
      source: "curated",
      popularity: 75,
      tags: ["Web Dev", "UX"],
    },
    {
      id: "curated-tech-7",
      name: "MIT Technology Review",
      description: "Technology news and analysis",
      feedUrl: "https://www.technologyreview.com/feed/",
      siteUrl: "https://www.technologyreview.com",
      category: "tech-programming",
      source: "curated",
      popularity: 88,
      tags: ["Tech News", "Research"],
    },
    {
      id: "curated-tech-8",
      name: "Wired",
      description: "Technology and culture",
      feedUrl: "https://www.wired.com/feed/rss",
      siteUrl: "https://www.wired.com",
      category: "tech-programming",
      source: "curated",
      popularity: 92,
      tags: ["Tech News", "Culture"],
    },
    {
      id: "curated-tech-9",
      name: "The GitHub Blog",
      description: "Updates from GitHub",
      feedUrl: "https://github.blog/feed/",
      siteUrl: "https://github.blog",
      category: "tech-programming",
      source: "curated",
      popularity: 87,
      tags: ["GitHub", "Developer Tools"],
    },
    {
      id: "curated-tech-10",
      name: "Hacking with Swift",
      description: "Swift and iOS development tutorials",
      feedUrl: "https://www.hackingwithswift.com/articles/rss",
      siteUrl: "https://www.hackingwithswift.com",
      category: "tech-programming",
      source: "curated",
      popularity: 78,
      tags: ["Swift", "iOS"],
    },
    {
      id: "curated-tech-11",
      name: "Mozilla Hacks",
      description: "Web development articles from Mozilla",
      feedUrl: "https://hacks.mozilla.org/feed/",
      siteUrl: "https://hacks.mozilla.org",
      category: "tech-programming",
      source: "curated",
      popularity: 82,
      tags: ["Web Dev", "Mozilla"],
    },
    {
      id: "curated-tech-12",
      name: "web.dev",
      description: "Google's resource for modern web development",
      feedUrl: "https://web.dev/feed.xml",
      siteUrl: "https://web.dev",
      category: "tech-programming",
      source: "curated",
      popularity: 86,
      tags: ["Web Dev", "Google"],
    },
    {
      id: "curated-tech-13",
      name: "The Changelog",
      description: "News and podcasts for developers",
      feedUrl: "https://changelog.com/feed",
      siteUrl: "https://changelog.com",
      category: "tech-programming",
      source: "curated",
      popularity: 84,
      tags: ["News", "Podcasts"],
    },
    {
      id: "curated-tech-14",
      name: "InfoQ",
      description: "Software development news and articles",
      feedUrl: "https://www.infoq.com/feed/",
      siteUrl: "https://www.infoq.com",
      category: "tech-programming",
      source: "curated",
      popularity: 82,
      tags: ["Software", "Architecture"],
    },
    {
      id: "curated-tech-15",
      name: "Coding Horror",
      description: "Programming and human factors by Jeff Atwood",
      feedUrl: "https://blog.codinghorror.com/rss/",
      siteUrl: "https://blog.codinghorror.com",
      category: "tech-programming",
      source: "curated",
      popularity: 80,
      tags: ["Programming", "Essays"],
    },
  ],
  "gaming": [
    {
      id: "curated-game-1",
      name: "PC Gamer",
      description: "PC gaming news, reviews, and features",
      feedUrl: "https://www.pcgamer.com/rss/",
      siteUrl: "https://www.pcgamer.com",
      category: "gaming",
      source: "curated",
      popularity: 95,
      tags: ["PC Gaming", "Reviews"],
    },
    {
      id: "curated-game-2",
      name: "Rock Paper Shotgun",
      description: "PC gaming news with personality",
      feedUrl: "https://www.rockpapershotgun.com/feed",
      siteUrl: "https://www.rockpapershotgun.com",
      category: "gaming",
      source: "curated",
      popularity: 90,
      tags: ["PC Gaming", "Indie"],
    },
    {
      id: "curated-game-3",
      name: "Eurogamer",
      description: "European gaming news and reviews",
      feedUrl: "https://www.eurogamer.net/feed",
      siteUrl: "https://www.eurogamer.net",
      category: "gaming",
      source: "curated",
      popularity: 88,
      tags: ["Gaming", "News"],
    },
    {
      id: "curated-game-4",
      name: "Polygon",
      description: "Gaming and entertainment news",
      feedUrl: "https://www.polygon.com/rss/index.xml",
      siteUrl: "https://www.polygon.com",
      category: "gaming",
      source: "curated",
      popularity: 92,
      tags: ["Gaming", "Entertainment"],
    },
    {
      id: "curated-game-5",
      name: "Kotaku",
      description: "Gaming news and culture",
      feedUrl: "https://kotaku.com/rss",
      siteUrl: "https://kotaku.com",
      category: "gaming",
      source: "curated",
      popularity: 87,
      tags: ["Gaming", "Culture"],
    },
    {
      id: "curated-game-6",
      name: "IGN",
      description: "Video game, movie and TV reviews",
      feedUrl: "https://feeds.feedburner.com/ign/all",
      siteUrl: "https://www.ign.com",
      category: "gaming",
      source: "curated",
      popularity: 93,
      tags: ["Gaming", "Reviews"],
    },
    {
      id: "curated-game-7",
      name: "GameSpot",
      description: "Video game news and reviews",
      feedUrl: "https://www.gamespot.com/feeds/mashup/",
      siteUrl: "https://www.gamespot.com",
      category: "gaming",
      source: "curated",
      popularity: 86,
      tags: ["Gaming", "Reviews"],
    },
    {
      id: "curated-game-8",
      name: "Destructoid",
      description: "Video game news and reviews",
      feedUrl: "https://www.destructoid.com/feed/",
      siteUrl: "https://www.destructoid.com",
      category: "gaming",
      source: "curated",
      popularity: 80,
      tags: ["Gaming", "News"],
    },
    {
      id: "curated-game-9",
      name: "GamesRadar+",
      description: "Gaming news across all platforms",
      feedUrl: "https://www.gamesradar.com/rss/",
      siteUrl: "https://www.gamesradar.com",
      category: "gaming",
      source: "curated",
      popularity: 84,
      tags: ["Gaming", "Multiplatform"],
    },
    {
      id: "curated-game-10",
      name: "Gamasutra",
      description: "Game development industry news",
      feedUrl: "https://www.gamedeveloper.com/rss.xml",
      siteUrl: "https://www.gamedeveloper.com",
      category: "gaming",
      source: "curated",
      popularity: 78,
      tags: ["Game Dev", "Industry"],
    },
  ],
  "entertainment-media": [
    {
      id: "curated-ent-1",
      name: "The A.V. Club",
      description: "Pop culture reviews and news",
      feedUrl: "https://www.avclub.com/rss",
      siteUrl: "https://www.avclub.com",
      category: "entertainment-media",
      source: "curated",
      popularity: 90,
      tags: ["TV", "Movies", "Reviews"],
    },
    {
      id: "curated-ent-2",
      name: "Pitchfork",
      description: "Music reviews and news",
      feedUrl: "https://pitchfork.com/feed/feed-news/rss",
      siteUrl: "https://pitchfork.com",
      category: "entertainment-media",
      source: "curated",
      popularity: 88,
      tags: ["Music", "Reviews"],
    },
    {
      id: "curated-ent-3",
      name: "IndieWire",
      description: "Independent film news and criticism",
      feedUrl: "https://www.indiewire.com/feed/",
      siteUrl: "https://www.indiewire.com",
      category: "entertainment-media",
      source: "curated",
      popularity: 82,
      tags: ["Movies", "Film"],
    },
    {
      id: "curated-ent-4",
      name: "Screen Rant",
      description: "Movie and TV news, reviews, and features",
      feedUrl: "https://screenrant.com/feed/",
      siteUrl: "https://screenrant.com",
      category: "entertainment-media",
      source: "curated",
      popularity: 85,
      tags: ["Movies", "TV"],
    },
    {
      id: "curated-ent-5",
      name: "Rolling Stone",
      description: "Music, culture, and politics",
      feedUrl: "https://www.rollingstone.com/feed/",
      siteUrl: "https://www.rollingstone.com",
      category: "entertainment-media",
      source: "curated",
      popularity: 92,
      tags: ["Music", "Culture"],
    },
    {
      id: "curated-ent-6",
      name: "Variety",
      description: "Entertainment industry news",
      feedUrl: "https://variety.com/feed/",
      siteUrl: "https://variety.com",
      category: "entertainment-media",
      source: "curated",
      popularity: 95,
      tags: ["Hollywood", "Industry"],
    },
    {
      id: "curated-ent-7",
      name: "The Hollywood Reporter",
      description: "Entertainment news and analysis",
      feedUrl: "https://www.hollywoodreporter.com/feed/",
      siteUrl: "https://www.hollywoodreporter.com",
      category: "entertainment-media",
      source: "curated",
      popularity: 93,
      tags: ["Hollywood", "News"],
    },
    {
      id: "curated-ent-8",
      name: "Consequence",
      description: "Music, film, and TV news",
      feedUrl: "https://consequence.net/feed/",
      siteUrl: "https://consequence.net",
      category: "entertainment-media",
      source: "curated",
      popularity: 80,
      tags: ["Music", "Film"],
    },
    {
      id: "curated-ent-9",
      name: "Stereogum",
      description: "Music news and reviews",
      feedUrl: "https://www.stereogum.com/feed/",
      siteUrl: "https://www.stereogum.com",
      category: "entertainment-media",
      source: "curated",
      popularity: 78,
      tags: ["Music", "Indie"],
    },
  ],
  "news-current-events": [
    {
      id: "curated-news-1",
      name: "BBC News",
      description: "Breaking news and analysis from the BBC",
      feedUrl: "https://feeds.bbci.co.uk/news/rss.xml",
      siteUrl: "https://www.bbc.com/news",
      category: "news-current-events",
      source: "curated",
      popularity: 100,
      tags: ["World News", "Breaking"],
    },
    {
      id: "curated-news-2",
      name: "NPR News",
      description: "National and international news from NPR",
      feedUrl: "https://feeds.npr.org/1001/rss.xml",
      siteUrl: "https://www.npr.org",
      category: "news-current-events",
      source: "curated",
      popularity: 95,
      tags: ["US News", "World News"],
    },
    {
      id: "curated-news-3",
      name: "The Guardian - World",
      description: "World news from The Guardian",
      feedUrl: "https://www.theguardian.com/world/rss",
      siteUrl: "https://www.theguardian.com/world",
      category: "news-current-events",
      source: "curated",
      popularity: 92,
      tags: ["World News"],
    },
    {
      id: "curated-news-4",
      name: "Al Jazeera English",
      description: "International news and current affairs",
      feedUrl: "https://www.aljazeera.com/xml/rss/all.xml",
      siteUrl: "https://www.aljazeera.com",
      category: "news-current-events",
      source: "curated",
      popularity: 98,
      tags: ["World News", "Middle East"],
    },
    {
      id: "curated-news-5",
      name: "CNN Top Stories",
      description: "Breaking news from CNN",
      feedUrl: "http://rss.cnn.com/rss/cnn_topstories.rss",
      siteUrl: "https://www.cnn.com",
      category: "news-current-events",
      source: "curated",
      popularity: 94,
      tags: ["Breaking", "US News"],
    },
    {
      id: "curated-news-6",
      name: "ABC News",
      description: "Top headlines from ABC News",
      feedUrl: "https://abcnews.go.com/abcnews/topstories",
      siteUrl: "https://abcnews.go.com",
      category: "news-current-events",
      source: "curated",
      popularity: 90,
      tags: ["US News", "Breaking"],
    },
    {
      id: "curated-news-7",
      name: "BBC News - Technology",
      description: "Technology news from BBC",
      feedUrl: "https://feeds.bbci.co.uk/news/technology/rss.xml",
      siteUrl: "https://www.bbc.com/news/technology",
      category: "news-current-events",
      source: "curated",
      popularity: 88,
      tags: ["Tech", "News"],
    },
    {
      id: "curated-news-8",
      name: "The Guardian - Technology",
      description: "Technology news from The Guardian",
      feedUrl: "https://www.theguardian.com/uk/technology/rss",
      siteUrl: "https://www.theguardian.com/technology",
      category: "news-current-events",
      source: "curated",
      popularity: 86,
      tags: ["Tech", "News"],
    },
    {
      id: "curated-news-9",
      name: "NPR Technology",
      description: "Technology stories from NPR",
      feedUrl: "https://feeds.npr.org/1019/rss.xml",
      siteUrl: "https://www.npr.org/sections/technology",
      category: "news-current-events",
      source: "curated",
      popularity: 84,
      tags: ["Tech", "News"],
    },
    {
      id: "curated-news-10",
      name: "New York Times World",
      description: "World news from the New York Times",
      feedUrl: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
      siteUrl: "https://www.nytimes.com/section/world",
      category: "news-current-events",
      source: "curated",
      popularity: 96,
      tags: ["World News", "Breaking"],
    },
  ],
  "podcasts-newsletters": [
    {
      id: "curated-pod-1",
      name: "This American Life",
      description: "True stories, told well",
      feedUrl: "https://www.thisamericanlife.org/podcast/rss.xml",
      siteUrl: "https://www.thisamericanlife.org",
      category: "podcasts-newsletters",
      source: "curated",
      popularity: 100,
      tags: ["Podcast", "Stories"],
      isPodcast: true,
    },
    {
      id: "curated-pod-2",
      name: "99% Invisible",
      description: "Design and architecture podcast",
      feedUrl: "https://feeds.simplecast.com/BqbsxVfO",
      siteUrl: "https://99percentinvisible.org",
      category: "podcasts-newsletters",
      source: "curated",
      popularity: 95,
      tags: ["Podcast", "Design"],
      isPodcast: true,
    },
    {
      id: "curated-pod-3",
      name: "Radiolab",
      description: "Science and philosophy stories",
      feedUrl: "https://feeds.simplecast.com/EmVW7VGp",
      siteUrl: "https://radiolab.org",
      category: "podcasts-newsletters",
      source: "curated",
      popularity: 92,
      tags: ["Podcast", "Science"],
      isPodcast: true,
    },
    {
      id: "curated-pod-4",
      name: "The Vergecast",
      description: "Tech news and discussion",
      feedUrl: "https://feeds.megaphone.fm/vergecast",
      siteUrl: "https://www.theverge.com/the-vergecast",
      category: "podcasts-newsletters",
      source: "curated",
      popularity: 88,
      tags: ["Podcast", "Tech"],
      isPodcast: true,
    },
    {
      id: "curated-pod-5",
      name: "Dense Discovery",
      description: "Weekly newsletter on design, tech, and sustainability",
      feedUrl: "https://www.densediscovery.com/feed",
      siteUrl: "https://www.densediscovery.com",
      category: "podcasts-newsletters",
      source: "curated",
      popularity: 85,
      tags: ["Newsletter", "Design"],
      isNewsletter: true,
    },
    {
      id: "curated-pod-6",
      name: "JavaScript Weekly",
      description: "Weekly roundup of JavaScript news and articles",
      feedUrl: "https://javascriptweekly.com/rss/",
      siteUrl: "https://javascriptweekly.com",
      category: "podcasts-newsletters",
      source: "curated",
      popularity: 82,
      tags: ["Newsletter", "JavaScript"],
      isNewsletter: true,
    },
    {
      id: "curated-pod-7",
      name: "Node Weekly",
      description: "Weekly Node.js news and links",
      feedUrl: "https://nodeweekly.com/rss/",
      siteUrl: "https://nodeweekly.com",
      category: "podcasts-newsletters",
      source: "curated",
      popularity: 90,
      tags: ["Newsletter", "Node.js"],
      isNewsletter: true,
    },
    {
      id: "curated-pod-8",
      name: "React Status",
      description: "Weekly React news and links",
      feedUrl: "https://react.statuscode.com/rss/",
      siteUrl: "https://react.statuscode.com",
      category: "podcasts-newsletters",
      source: "curated",
      popularity: 87,
      tags: ["Newsletter", "React"],
      isNewsletter: true,
    },
    {
      id: "curated-pod-9",
      name: "Planet Money",
      description: "NPR podcast about the economy",
      feedUrl: "https://feeds.npr.org/510289/podcast.xml",
      siteUrl: "https://www.npr.org/sections/money/",
      category: "podcasts-newsletters",
      source: "curated",
      popularity: 86,
      tags: ["Podcast", "Economics"],
      isPodcast: true,
    },
    {
      id: "curated-pod-10",
      name: "Software Engineering Daily",
      description: "Technical interviews about software",
      feedUrl: "https://softwareengineeringdaily.com/feed/podcast/",
      siteUrl: "https://softwareengineeringdaily.com",
      category: "podcasts-newsletters",
      source: "curated",
      popularity: 80,
      tags: ["Podcast", "Software"],
      isPodcast: true,
    },
  ],
  "indie-blogs": [
    {
      id: "curated-indie-1",
      name: "Julia Evans",
      description: "Programming explanations with comics",
      feedUrl: "https://jvns.ca/atom.xml",
      siteUrl: "https://jvns.ca",
      category: "indie-blogs",
      source: "curated",
      popularity: 100,
      tags: ["Programming", "Learning"],
    },
    {
      id: "curated-indie-2",
      name: "Dan Luu",
      description: "In-depth engineering analysis",
      feedUrl: "https://danluu.com/atom.xml",
      siteUrl: "https://danluu.com",
      category: "indie-blogs",
      source: "curated",
      popularity: 95,
      tags: ["Engineering", "Analysis"],
    },
    {
      id: "curated-indie-3",
      name: "Paul Graham",
      description: "Essays on startups and programming",
      feedUrl: "http://www.aaronsw.com/2002/feeds/pgessays.rss",
      siteUrl: "http://paulgraham.com",
      category: "indie-blogs",
      source: "curated",
      popularity: 98,
      tags: ["Startups", "Essays"],
    },
    {
      id: "curated-indie-4",
      name: "Simon Willison",
      description: "Web development and AI tools",
      feedUrl: "https://simonwillison.net/atom/everything/",
      siteUrl: "https://simonwillison.net",
      category: "indie-blogs",
      source: "curated",
      popularity: 92,
      tags: ["Web Dev", "AI"],
    },
    {
      id: "curated-indie-5",
      name: "Overreacted",
      description: "Dan Abramov on React and JavaScript",
      feedUrl: "https://overreacted.io/rss.xml",
      siteUrl: "https://overreacted.io",
      category: "indie-blogs",
      source: "curated",
      popularity: 90,
      tags: ["React", "JavaScript"],
    },
    {
      id: "curated-indie-6",
      name: "Kent C. Dodds",
      description: "React, testing, and JavaScript best practices",
      feedUrl: "https://kentcdodds.com/blog/rss.xml",
      siteUrl: "https://kentcdodds.com",
      category: "indie-blogs",
      source: "curated",
      popularity: 88,
      tags: ["React", "Testing"],
    },
    {
      id: "curated-indie-7",
      name: "Wait But Why",
      description: "Long-form explanatory posts",
      feedUrl: "https://waitbutwhy.com/feed",
      siteUrl: "https://waitbutwhy.com",
      category: "indie-blogs",
      source: "curated",
      popularity: 94,
      tags: ["Essays", "Explainers"],
    },
    {
      id: "curated-indie-8",
      name: "Derek Sivers",
      description: "Thoughts on life, business, and creativity",
      feedUrl: "https://sive.rs/en.atom",
      siteUrl: "https://sive.rs",
      category: "indie-blogs",
      source: "curated",
      popularity: 85,
      tags: ["Life", "Business"],
    },
    {
      id: "curated-indie-9",
      name: "Seth Godin",
      description: "Daily blog on marketing and leadership",
      feedUrl: "https://seths.blog/feed/",
      siteUrl: "https://seths.blog",
      category: "indie-blogs",
      source: "curated",
      popularity: 87,
      tags: ["Marketing", "Leadership"],
    },
    {
      id: "curated-indie-10",
      name: "Cal Newport",
      description: "Deep work and productivity",
      feedUrl: "https://calnewport.com/feed/",
      siteUrl: "https://calnewport.com",
      category: "indie-blogs",
      source: "curated",
      popularity: 86,
      tags: ["Productivity", "Focus"],
    },
    {
      id: "curated-indie-11",
      name: "James Clear",
      description: "Habits and continuous improvement",
      feedUrl: "https://jamesclear.com/feed",
      siteUrl: "https://jamesclear.com",
      category: "indie-blogs",
      source: "curated",
      popularity: 89,
      tags: ["Habits", "Productivity"],
    },
    {
      id: "curated-indie-12",
      name: "Maggie Appleton",
      description: "Visual essays on technology and design",
      feedUrl: "https://maggieappleton.com/rss.xml",
      siteUrl: "https://maggieappleton.com",
      category: "indie-blogs",
      source: "curated",
      popularity: 82,
      tags: ["Design", "Essays"],
    },
  ],
  "lifestyle-other": [
    {
      id: "curated-life-1",
      name: "Lifehacker",
      description: "Tips for a more efficient life",
      feedUrl: "https://lifehacker.com/feed/rss",
      siteUrl: "https://lifehacker.com",
      category: "lifestyle-other",
      source: "curated",
      popularity: 90,
      tags: ["Productivity", "Life Tips"],
    },
    {
      id: "curated-life-2",
      name: "Science Daily",
      description: "Latest science news and research",
      feedUrl: "https://www.sciencedaily.com/rss/all.xml",
      siteUrl: "https://www.sciencedaily.com",
      category: "lifestyle-other",
      source: "curated",
      popularity: 85,
      tags: ["Science", "Research"],
    },
    {
      id: "curated-life-3",
      name: "Quanta Magazine",
      description: "In-depth science and math journalism",
      feedUrl: "https://www.quantamagazine.org/feed/",
      siteUrl: "https://www.quantamagazine.org",
      category: "lifestyle-other",
      source: "curated",
      popularity: 95,
      tags: ["Science", "Math"],
    },
    {
      id: "curated-life-4",
      name: "ESPN",
      description: "Sports news and scores",
      feedUrl: "https://www.espn.com/espn/rss/news",
      siteUrl: "https://www.espn.com",
      category: "lifestyle-other",
      source: "curated",
      popularity: 92,
      tags: ["Sports", "News"],
    },
    {
      id: "curated-life-5",
      name: "Space.com",
      description: "Space exploration and astronomy news",
      feedUrl: "https://www.space.com/feeds/all",
      siteUrl: "https://www.space.com",
      category: "lifestyle-other",
      source: "curated",
      popularity: 88,
      tags: ["Space", "Science"],
    },
    {
      id: "curated-life-6",
      name: "New Scientist",
      description: "Science and technology news",
      feedUrl: "https://www.newscientist.com/feed/home/",
      siteUrl: "https://www.newscientist.com",
      category: "lifestyle-other",
      source: "curated",
      popularity: 86,
      tags: ["Science", "Tech"],
    },
    {
      id: "curated-life-7",
      name: "Nature News",
      description: "Latest research news from Nature",
      feedUrl: "https://www.nature.com/nature.rss",
      siteUrl: "https://www.nature.com",
      category: "lifestyle-other",
      source: "curated",
      popularity: 90,
      tags: ["Science", "Research"],
    },
    {
      id: "curated-life-8",
      name: "Popular Science",
      description: "Science and technology for everyone",
      feedUrl: "https://www.popsci.com/feed/",
      siteUrl: "https://www.popsci.com",
      category: "lifestyle-other",
      source: "curated",
      popularity: 84,
      tags: ["Science", "Tech"],
    },
    {
      id: "curated-life-9",
      name: "Aeon Essays",
      description: "Deep essays on philosophy and ideas",
      feedUrl: "https://aeon.co/feed.rss",
      siteUrl: "https://aeon.co",
      category: "lifestyle-other",
      source: "curated",
      popularity: 82,
      tags: ["Philosophy", "Essays"],
    },
    {
      id: "curated-life-10",
      name: "Smithsonian Magazine",
      description: "Science, history, and culture stories",
      feedUrl: "https://www.smithsonianmag.com/rss/latest_articles/",
      siteUrl: "https://www.smithsonianmag.com",
      category: "lifestyle-other",
      source: "curated",
      popularity: 80,
      tags: ["Science", "Culture"],
    },
  ],
};

/**
 * Get all curated feeds for a category
 */
export function getCuratedFeedsForCategory(category: DiscoverCategory): DiscoverFeed[] {
  return CURATED_FEEDS[category] || [];
}

/**
 * Get all curated feeds across all categories
 */
export function getAllCuratedFeeds(): DiscoverFeed[] {
  return Object.values(CURATED_FEEDS).flat();
}

/**
 * Search curated feeds by name, description, or tags
 */
export function searchCuratedFeeds(query: string): DiscoverFeed[] {
  const lowerQuery = query.toLowerCase();
  return getAllCuratedFeeds().filter(
    (feed) =>
      feed.name.toLowerCase().includes(lowerQuery) ||
      feed.description?.toLowerCase().includes(lowerQuery) ||
      feed.tags?.some((tag) => tag.toLowerCase().includes(lowerQuery))
  );
}
